### PR TITLE
Add colortemperature light

### PR DESCRIPTION
**Pull request by dj95**
Hi @c0defre4k,

I really appreciate, that you've extended the functionality of this project in your fork! Do you mind, if we back port it with this pull request? :)

### CODE REVIEW

**Comment by c0defre4k** [comment]
Thanks for asking! Of course you can merge my changes.

One thing about my docker integration. It would be nice if log output could be set to stdout. Ideally all the config options could also be set via environment variables or command line flags. It seems that your config library supports that. Unfortunately I'm not very familiar with go, maybe you can have a look at that?

**Comment by dj95** [comment]
Sure! 

Do you mind to remove the Dockerfile from the PR? I'll then provide a new multi-stage Dockerfile, which also builds the binary. 

I'm not quite familiar with the S6 overlay, but in the first look it seems a bit bloated. The huekit binary could just run within a scratch image, such that it requires less resources (instead of running supervisord etc.).

Maybe I'll get this implemented up to the weekend. Will then provide a new PR and mention you, such that you get notified.

**Comment by c0defre4k** [comment]
Yeah splitting this up into 2 PRs is a good idea. I think we can omit S6.  I don't know if the go binary has its own signal handlers. If not we should have a look at https://github.com/krallin/tini. Otherwise running it directly should not be a problem I guess.

**Comment by dj95** [comment]
Standard signalling should work, such that SIGTERM and SIGKILL will be able to terminate the binary. Custom signals (like reload via SIGUSR1 as in nginx) must be implemented additionally.

I've provided a pull request with your requested changes. Feel free to test it and leave a comment. https://github.com/dj95/huekit/pull/4

As soon as you then removed the dockerfile from this repo, I'd like to merge the changes.

**Pull request merged**
